name: Dockerize and Deploy Next.js App

on:
  push:
    branches:
      - main

env:
  AZURE_RG_NAME: catsRG
  ACR_NAME: catsk8s
  CONTAINER_IMAGE_NAME: nextapp

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: ${{ env.ACR_NAME }}.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ env.ACR_NAME }}.azurecr.io/${{ env.CONTAINER_IMAGE_NAME}}:latest

#      - name: Deploy to AKS
#        uses: azure/aks-set-image@v1
#        with:
#          resource-group: <your-resource-group-name>
#          cluster-name: <your-aks-cluster-name>
#          container-image-name: <your-acr-name>.azurecr.io/<your-image-name>:latest
