name: Deploy NextApp to AKS

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  AZURE_RG_NAME: catsRG
  ACR_NAME: catsk8s
  CONTAINER_IMAGE_NAME: nextapp
  AKS_CLUSTER_NAME: catsk8s
  CHART_PATH: "./chart/"
  CHART_OVERRIDE_PATH: "./environments"
  ENVIRONMENT: "prod"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: ${{ env.ACR_NAME }}.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ env.ACR_NAME }}.azurecr.io/${{ env.CONTAINER_IMAGE_NAME}}:latest

      - name: Login to Azure
        uses: azure/login@v1
        with:
           creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Use kubelogin to configure your kubeconfig for Azure auth
      - name: Set up kubelogin for non-interactive login
        uses: azure/use-kubelogin@v1
        with:
          kubelogin-version: 'v0.0.25'

      - name: Set AKS Context
        uses: azure/aks-set-context@v3
        with:
           creds: ${{ secrets.AZURE_CREDENTIALS }}
           cluster-name: ${{ env.AKS_CLUSTER_NAME }}
           resource-group: ${{ env.AZURE_RG_NAME }}

      # Runs Helm to create manifest files
      - name: Bake deployment
        uses: azure/k8s-bake@v2
        with:
          renderEngine: "helm"
          helmChart: ${{ env.CHART_PATH }}
          overrideFiles: ${{ env.CHART_OVERRIDE_PATH }}/${{ env.ENVIRONMENT }}.yml
          overrides: |
            image.name:${{ env.ACR_NAME }}.azurecr.io/${{ env.CONTAINER_IMAGE_NAME }}
            image.tag:latest
          helm-version: "latest"
        id: bake

      - name: Deploy application
        uses: Azure/cli@v1.0.9
        with:
          azcliversion: 2.56.0
          inlineScript: |
            cat ${{ steps.bake.outputs.manifestsBundle }} >> manifest.yml
            az aks command invoke --resource-group ${{ env.AZURE_RG_NAME }} --name ${{ env.AKS_CLUSTER_NAME }} --file manifest.yml --command "kubectl apply -f manifest.yml"
